/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import hospital.management.system.connection.UpdateBloodGroupConnect;
import javax.swing.JOptionPane;

/**
 *
 * @author Hashan
 */
public class AddBloodGroup extends javax.swing.JFrame {

    /**
     * Creates new form AddBloodGroup
     */
    //declearing global variables
    private int patientId;

    public AddBloodGroup() {
        initComponents();
    }

    // constructor overloading
    public AddBloodGroup(int patientId) {
        initComponents();
        this.patientId = patientId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultantName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bloodGroupCombo = new javax.swing.JComboBox<>();
        OkButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultantName.setBackground(new java.awt.Color(51, 51, 51));
        consultantName.setFont(new java.awt.Font("Quicksand", 0, 36)); // NOI18N
        consultantName.setForeground(new java.awt.Color(217, 222, 225));
        consultantName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultantName.setText("Add Blood Group");
        jPanel1.add(consultantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 90));

        jPanel2.setBackground(new java.awt.Color(67, 101, 112));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bloodGroupCombo.setBackground(new java.awt.Color(67, 101, 112));
        bloodGroupCombo.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        bloodGroupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A +", "A -", "B +", "B -", "AB +", "AB -", "O +", "O -" }));
        bloodGroupCombo.setFocusable(false);
        jPanel2.add(bloodGroupCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 40));

        OkButton.setBackground(new java.awt.Color(51, 51, 51));
        OkButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        OkButton.setForeground(new java.awt.Color(255, 255, 255));
        OkButton.setText("OK");
        OkButton.setBorder(null);
        OkButton.setFocusable(false);
        OkButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OkButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        jPanel2.add(OkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 90, 40));

        CancelButton.setBackground(new java.awt.Color(51, 51, 51));
        CancelButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setText("CANCEL");
        CancelButton.setBorder(null);
        CancelButton.setFocusable(false);
        CancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CancelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 90, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        String bloodType = bloodGroupCombo.getSelectedItem().toString();

        //updating the blood group
        UpdateBloodGroupConnect bloodGroup = new UpdateBloodGroupConnect();
        int result = bloodGroup.updateData(bloodType, patientId);

        if (result == 1) {
            JOptionPane.showMessageDialog(this, "Blood Group Updated");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Update Failed");
        }
    }//GEN-LAST:event_OkButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBloodGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton OkButton;
    private javax.swing.JComboBox<String> bloodGroupCombo;
    private javax.swing.JLabel consultantName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
