/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import hospital.management.system.connection.AddEmployeeConnect;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Hashan
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
    }
    
    //adding employee data into the database
    public void addEmployeeFinal(int employee_id, String name, String gender, String addressLine1, String addressLine2,
            String city, String specialization, int contact, String dateOfJob, String type,String password,String adminRight) {

        AddEmployeeConnect addConnect = new AddEmployeeConnect();
        int result = addConnect.updateData(employee_id, name, gender, addressLine1,
                addressLine2, city, specialization, contact, dateOfJob, type,password,adminRight);
        if (result == 1) {
            JOptionPane.showMessageDialog(this, "Successfull");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorGenderButtonGroup = new javax.swing.ButtonGroup();
        nurseGenderButtonGroup = new javax.swing.ButtonGroup();
        maintenanceGenderButtonGroup = new javax.swing.ButtonGroup();
        receptionGenderButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        doctorSpecialization = new javax.swing.JTextField();
        doctorEmployeeId = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        doctorName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        doctorAddressLine1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        doctorAddressLine2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        doctorCity = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        doctorConfirmButton = new javax.swing.JButton();
        doctorRadioFemale = new javax.swing.JRadioButton();
        doctorRadioMale = new javax.swing.JRadioButton();
        doctorContact = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        doctorAdminCheck = new javax.swing.JCheckBox();
        doctorDateOfJob = new com.toedter.calendar.JDateChooser();
        doctorPassword = new javax.swing.JPasswordField();
        doctorReEnterPassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nurseEmployeeId = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        nurseName = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nurseAddressLine1 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        nurseAddressLine2 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        nurseCity = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        nurseConfirmButton = new javax.swing.JButton();
        nurseContact = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        nurseRadioMale = new javax.swing.JRadioButton();
        nurseRadioFemale = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        nurseAdminCheck = new javax.swing.JCheckBox();
        nurseDateOfJob = new com.toedter.calendar.JDateChooser();
        nursePassword = new javax.swing.JPasswordField();
        nurseReEnterPassword = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        maintenanceEmployeeId = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        maintenanceName = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        maintenanceAddressLine1 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        maintenanceAddressLine2 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        maintenanceCity = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        maintenanceConfirmButton = new javax.swing.JButton();
        maintenanceContact = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        maintenanceRadioMale = new javax.swing.JRadioButton();
        maintenanceRadioFemale = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        maintenanceAdminCheck = new javax.swing.JCheckBox();
        maintenanceDateOfJob = new com.toedter.calendar.JDateChooser();
        maintenanceReEnterPassword = new javax.swing.JPasswordField();
        maintenancePassword = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        receptionEmployeeId = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        receptionName = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        receptionAddressLine1 = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        receptionAddressLine2 = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        receptionCity = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();
        receptionConfirmButton = new javax.swing.JButton();
        receptionContact = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jSeparator39 = new javax.swing.JSeparator();
        receptionRadioMale = new javax.swing.JRadioButton();
        receptionRadioFemale = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jSeparator41 = new javax.swing.JSeparator();
        receptionAdminCheck = new javax.swing.JCheckBox();
        receptionDateOfJob = new com.toedter.calendar.JDateChooser();
        receptionPassword = new javax.swing.JPasswordField();
        receptionReEnterPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 152, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 152, 216));
        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add an  Employee");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, 70));

        jLabel7.setBackground(new java.awt.Color(0, 153, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add User Group Man Man Filled-100.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, 150));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 230, 10));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 190, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 650));

        jTabbedPane1.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Employee ID");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, 30));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Specialization");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 110, 30));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date of Job");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 90, 30));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Employee Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, 30));

        doctorSpecialization.setBackground(new java.awt.Color(51, 51, 51));
        doctorSpecialization.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        doctorSpecialization.setForeground(new java.awt.Color(255, 255, 255));
        doctorSpecialization.setBorder(null);
        doctorSpecialization.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(doctorSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 190, 30));

        doctorEmployeeId.setBackground(new java.awt.Color(51, 51, 51));
        doctorEmployeeId.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        doctorEmployeeId.setForeground(new java.awt.Color(255, 255, 255));
        doctorEmployeeId.setBorder(null);
        doctorEmployeeId.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(doctorEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 190, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 190, 10));

        doctorName.setBackground(new java.awt.Color(51, 51, 51));
        doctorName.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        doctorName.setForeground(new java.awt.Color(255, 255, 255));
        doctorName.setBorder(null);
        doctorName.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(doctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 190, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 190, 10));

        jSeparator15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 190, 10));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, 30));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address Line 1");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 30));

        doctorAddressLine1.setBackground(new java.awt.Color(51, 51, 51));
        doctorAddressLine1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        doctorAddressLine1.setForeground(new java.awt.Color(255, 255, 255));
        doctorAddressLine1.setBorder(null);
        doctorAddressLine1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(doctorAddressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, 30));

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 190, 10));

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address Line 2");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, 30));

        doctorAddressLine2.setBackground(new java.awt.Color(51, 51, 51));
        doctorAddressLine2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        doctorAddressLine2.setForeground(new java.awt.Color(255, 255, 255));
        doctorAddressLine2.setBorder(null);
        doctorAddressLine2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(doctorAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, 30));

        jSeparator13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 190, 10));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("City");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 100, 30));

        doctorCity.setBackground(new java.awt.Color(51, 51, 51));
        doctorCity.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        doctorCity.setForeground(new java.awt.Color(255, 255, 255));
        doctorCity.setBorder(null);
        doctorCity.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(doctorCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 190, 30));

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, 10));

        doctorConfirmButton.setBackground(new java.awt.Color(0, 152, 216));
        doctorConfirmButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        doctorConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        doctorConfirmButton.setText("Confirm");
        doctorConfirmButton.setBorder(null);
        doctorConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorConfirmButtonActionPerformed(evt);
            }
        });
        jPanel2.add(doctorConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 110, 40));

        doctorRadioFemale.setBackground(new java.awt.Color(51, 51, 51));
        doctorGenderButtonGroup.add(doctorRadioFemale);
        doctorRadioFemale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        doctorRadioFemale.setForeground(new java.awt.Color(255, 255, 255));
        doctorRadioFemale.setText("Female");
        jPanel2.add(doctorRadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        doctorRadioMale.setBackground(new java.awt.Color(51, 51, 51));
        doctorGenderButtonGroup.add(doctorRadioMale);
        doctorRadioMale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        doctorRadioMale.setForeground(new java.awt.Color(255, 255, 255));
        doctorRadioMale.setSelected(true);
        doctorRadioMale.setText("Male");
        jPanel2.add(doctorRadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        doctorContact.setBackground(new java.awt.Color(51, 51, 51));
        doctorContact.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        doctorContact.setForeground(new java.awt.Color(255, 255, 255));
        doctorContact.setBorder(null);
        doctorContact.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(doctorContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 190, 30));

        jLabel30.setBackground(new java.awt.Color(51, 51, 51));
        jLabel30.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Contact");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 90, 30));

        jSeparator27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 190, 10));

        jLabel33.setBackground(new java.awt.Color(51, 51, 51));
        jLabel33.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Password");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 90, 30));

        jSeparator30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 190, 10));

        jLabel34.setBackground(new java.awt.Color(51, 51, 51));
        jLabel34.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Re-enter Password");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, 30));

        jSeparator31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 190, 10));

        doctorAdminCheck.setBackground(new java.awt.Color(51, 51, 51));
        doctorAdminCheck.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        doctorAdminCheck.setForeground(new java.awt.Color(255, 255, 255));
        doctorAdminCheck.setText("Give administrator privileges");
        doctorAdminCheck.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doctorAdminCheck.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        doctorAdminCheck.setIconTextGap(6);
        jPanel2.add(doctorAdminCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 320, -1));

        doctorDateOfJob.setBackground(new java.awt.Color(51, 51, 51));
        doctorDateOfJob.setForeground(new java.awt.Color(255, 255, 255));
        doctorDateOfJob.setDateFormatString("yyyy-MM-dd");
        doctorDateOfJob.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        jPanel2.add(doctorDateOfJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 190, -1));

        doctorPassword.setBackground(new java.awt.Color(51, 51, 51));
        doctorPassword.setBorder(null);
        jPanel2.add(doctorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 190, 30));

        doctorReEnterPassword.setBackground(new java.awt.Color(51, 51, 51));
        doctorReEnterPassword.setBorder(null);
        jPanel2.add(doctorReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 190, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 630));

        jTabbedPane1.addTab("Doctor", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Employee ID");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 90, 30));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date of Job");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 90, 30));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Employee Name");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, 30));

        nurseEmployeeId.setBackground(new java.awt.Color(51, 51, 51));
        nurseEmployeeId.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        nurseEmployeeId.setForeground(new java.awt.Color(255, 255, 255));
        nurseEmployeeId.setBorder(null);
        nurseEmployeeId.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel6.add(nurseEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 190, 30));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 10));

        nurseName.setBackground(new java.awt.Color(51, 51, 51));
        nurseName.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        nurseName.setForeground(new java.awt.Color(255, 255, 255));
        nurseName.setBorder(null);
        nurseName.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel6.add(nurseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 190, 30));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 190, 10));

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Gender");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 90, 30));

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Address Line 1");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 30));

        nurseAddressLine1.setBackground(new java.awt.Color(51, 51, 51));
        nurseAddressLine1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        nurseAddressLine1.setForeground(new java.awt.Color(255, 255, 255));
        nurseAddressLine1.setBorder(null);
        nurseAddressLine1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel6.add(nurseAddressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 190, 30));

        jSeparator18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 190, 10));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Address Line 2");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 30));

        nurseAddressLine2.setBackground(new java.awt.Color(51, 51, 51));
        nurseAddressLine2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        nurseAddressLine2.setForeground(new java.awt.Color(255, 255, 255));
        nurseAddressLine2.setBorder(null);
        nurseAddressLine2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel6.add(nurseAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 190, 30));

        jSeparator19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 190, 10));

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("City");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 30));

        nurseCity.setBackground(new java.awt.Color(51, 51, 51));
        nurseCity.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        nurseCity.setForeground(new java.awt.Color(255, 255, 255));
        nurseCity.setBorder(null);
        nurseCity.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel6.add(nurseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 190, 30));

        jSeparator20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 190, 10));

        nurseConfirmButton.setBackground(new java.awt.Color(0, 152, 216));
        nurseConfirmButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        nurseConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        nurseConfirmButton.setText("Confirm");
        nurseConfirmButton.setBorder(null);
        nurseConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseConfirmButtonActionPerformed(evt);
            }
        });
        jPanel6.add(nurseConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 110, 40));

        nurseContact.setBackground(new java.awt.Color(51, 51, 51));
        nurseContact.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        nurseContact.setForeground(new java.awt.Color(255, 255, 255));
        nurseContact.setBorder(null);
        nurseContact.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel6.add(nurseContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 190, 30));

        jLabel31.setBackground(new java.awt.Color(51, 51, 51));
        jLabel31.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Contact");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 90, 30));

        jSeparator28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 190, 10));

        nurseRadioMale.setBackground(new java.awt.Color(51, 51, 51));
        nurseGenderButtonGroup.add(nurseRadioMale);
        nurseRadioMale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        nurseRadioMale.setForeground(new java.awt.Color(255, 255, 255));
        nurseRadioMale.setSelected(true);
        nurseRadioMale.setText("Male");
        jPanel6.add(nurseRadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        nurseRadioFemale.setBackground(new java.awt.Color(51, 51, 51));
        nurseGenderButtonGroup.add(nurseRadioFemale);
        nurseRadioFemale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        nurseRadioFemale.setForeground(new java.awt.Color(255, 255, 255));
        nurseRadioFemale.setText("Female");
        jPanel6.add(nurseRadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel35.setBackground(new java.awt.Color(51, 51, 51));
        jLabel35.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Password");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 90, 30));

        jSeparator32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 190, 10));

        jLabel36.setBackground(new java.awt.Color(51, 51, 51));
        jLabel36.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Re-enter Password");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 30));

        jSeparator33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 190, 10));

        nurseAdminCheck.setBackground(new java.awt.Color(51, 51, 51));
        nurseAdminCheck.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        nurseAdminCheck.setForeground(new java.awt.Color(255, 255, 255));
        nurseAdminCheck.setText("Give administrator privileges");
        nurseAdminCheck.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nurseAdminCheck.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nurseAdminCheck.setIconTextGap(6);
        jPanel6.add(nurseAdminCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 320, -1));

        nurseDateOfJob.setBackground(new java.awt.Color(51, 51, 51));
        nurseDateOfJob.setForeground(new java.awt.Color(255, 255, 255));
        nurseDateOfJob.setDateFormatString("yyyy-MM-dd");
        nurseDateOfJob.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        jPanel6.add(nurseDateOfJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 190, -1));

        nursePassword.setBackground(new java.awt.Color(51, 51, 51));
        nursePassword.setBorder(null);
        jPanel6.add(nursePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 190, 30));

        nurseReEnterPassword.setBackground(new java.awt.Color(51, 51, 51));
        nurseReEnterPassword.setBorder(null);
        jPanel6.add(nurseReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 190, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 630));

        jTabbedPane1.addTab("Nurse", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Employee ID");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 30));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date of Job");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 90, 30));

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Employee Name");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 30));

        maintenanceEmployeeId.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceEmployeeId.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        maintenanceEmployeeId.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceEmployeeId.setBorder(null);
        maintenanceEmployeeId.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel7.add(maintenanceEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, 30));

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 190, 10));

        maintenanceName.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceName.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        maintenanceName.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceName.setBorder(null);
        maintenanceName.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel7.add(maintenanceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 30));

        jSeparator16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 190, 10));

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Gender");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 30));

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Address Line 1");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 30));

        maintenanceAddressLine1.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceAddressLine1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        maintenanceAddressLine1.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceAddressLine1.setBorder(null);
        maintenanceAddressLine1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel7.add(maintenanceAddressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 190, 30));

        jSeparator23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 190, 10));

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Address Line 2");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 30));

        maintenanceAddressLine2.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceAddressLine2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        maintenanceAddressLine2.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceAddressLine2.setBorder(null);
        maintenanceAddressLine2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel7.add(maintenanceAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 190, 30));

        jSeparator24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 190, 10));

        jLabel29.setBackground(new java.awt.Color(51, 51, 51));
        jLabel29.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("City");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, 30));

        maintenanceCity.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceCity.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        maintenanceCity.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceCity.setBorder(null);
        maintenanceCity.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel7.add(maintenanceCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 190, 30));

        jSeparator25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 190, 10));

        maintenanceConfirmButton.setBackground(new java.awt.Color(0, 152, 216));
        maintenanceConfirmButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        maintenanceConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceConfirmButton.setText("Confirm");
        maintenanceConfirmButton.setBorder(null);
        maintenanceConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceConfirmButtonActionPerformed(evt);
            }
        });
        jPanel7.add(maintenanceConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 110, 40));

        maintenanceContact.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceContact.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        maintenanceContact.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceContact.setBorder(null);
        maintenanceContact.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel7.add(maintenanceContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 190, 30));

        jLabel32.setBackground(new java.awt.Color(51, 51, 51));
        jLabel32.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Contact");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 90, 30));

        jSeparator29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 190, 10));

        maintenanceRadioMale.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceGenderButtonGroup.add(maintenanceRadioMale);
        maintenanceRadioMale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        maintenanceRadioMale.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceRadioMale.setSelected(true);
        maintenanceRadioMale.setText("Male");
        jPanel7.add(maintenanceRadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        maintenanceRadioFemale.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceGenderButtonGroup.add(maintenanceRadioFemale);
        maintenanceRadioFemale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        maintenanceRadioFemale.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceRadioFemale.setText("Female");
        jPanel7.add(maintenanceRadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel37.setBackground(new java.awt.Color(51, 51, 51));
        jLabel37.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Password");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 90, 30));

        jSeparator34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 190, 10));

        jLabel38.setBackground(new java.awt.Color(51, 51, 51));
        jLabel38.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Re-enter Password");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, 30));

        jSeparator35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 190, 10));

        maintenanceAdminCheck.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceAdminCheck.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        maintenanceAdminCheck.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceAdminCheck.setText("Give administrator privileges");
        maintenanceAdminCheck.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maintenanceAdminCheck.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        maintenanceAdminCheck.setIconTextGap(6);
        jPanel7.add(maintenanceAdminCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 320, -1));

        maintenanceDateOfJob.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceDateOfJob.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceDateOfJob.setDateFormatString("yyyy-MM-dd");
        maintenanceDateOfJob.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        jPanel7.add(maintenanceDateOfJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 190, -1));

        maintenanceReEnterPassword.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceReEnterPassword.setBorder(null);
        jPanel7.add(maintenanceReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 190, 30));

        maintenancePassword.setBackground(new java.awt.Color(51, 51, 51));
        maintenancePassword.setBorder(null);
        jPanel7.add(maintenancePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 190, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 630));

        jTabbedPane1.addTab("Maintenance", jPanel5);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(51, 51, 51));
        jLabel39.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Employee ID");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 30));

        jLabel40.setBackground(new java.awt.Color(51, 51, 51));
        jLabel40.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Date of Job");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 90, 30));

        jLabel41.setBackground(new java.awt.Color(51, 51, 51));
        jLabel41.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Employee Name");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 30));

        receptionEmployeeId.setBackground(new java.awt.Color(51, 51, 51));
        receptionEmployeeId.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        receptionEmployeeId.setForeground(new java.awt.Color(255, 255, 255));
        receptionEmployeeId.setBorder(null);
        receptionEmployeeId.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel8.add(receptionEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, 30));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 190, 10));

        receptionName.setBackground(new java.awt.Color(51, 51, 51));
        receptionName.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        receptionName.setForeground(new java.awt.Color(255, 255, 255));
        receptionName.setBorder(null);
        receptionName.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel8.add(receptionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 30));

        jSeparator17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 190, 10));

        jLabel42.setBackground(new java.awt.Color(51, 51, 51));
        jLabel42.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Gender");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 30));

        jLabel43.setBackground(new java.awt.Color(51, 51, 51));
        jLabel43.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Address Line 1");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 30));

        receptionAddressLine1.setBackground(new java.awt.Color(51, 51, 51));
        receptionAddressLine1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        receptionAddressLine1.setForeground(new java.awt.Color(255, 255, 255));
        receptionAddressLine1.setBorder(null);
        receptionAddressLine1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel8.add(receptionAddressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 190, 30));

        jSeparator36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 190, 10));

        jLabel44.setBackground(new java.awt.Color(51, 51, 51));
        jLabel44.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Address Line 2");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 30));

        receptionAddressLine2.setBackground(new java.awt.Color(51, 51, 51));
        receptionAddressLine2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        receptionAddressLine2.setForeground(new java.awt.Color(255, 255, 255));
        receptionAddressLine2.setBorder(null);
        receptionAddressLine2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel8.add(receptionAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 190, 30));

        jSeparator37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 190, 10));

        jLabel45.setBackground(new java.awt.Color(51, 51, 51));
        jLabel45.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("City");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, 30));

        receptionCity.setBackground(new java.awt.Color(51, 51, 51));
        receptionCity.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        receptionCity.setForeground(new java.awt.Color(255, 255, 255));
        receptionCity.setBorder(null);
        receptionCity.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel8.add(receptionCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 190, 30));

        jSeparator38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 190, 10));

        receptionConfirmButton.setBackground(new java.awt.Color(0, 152, 216));
        receptionConfirmButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        receptionConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        receptionConfirmButton.setText("Confirm");
        receptionConfirmButton.setBorder(null);
        receptionConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionConfirmButtonActionPerformed(evt);
            }
        });
        jPanel8.add(receptionConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 110, 40));

        receptionContact.setBackground(new java.awt.Color(51, 51, 51));
        receptionContact.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        receptionContact.setForeground(new java.awt.Color(255, 255, 255));
        receptionContact.setBorder(null);
        receptionContact.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel8.add(receptionContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 190, 30));

        jLabel46.setBackground(new java.awt.Color(51, 51, 51));
        jLabel46.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Contact");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 90, 30));

        jSeparator39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 190, 10));

        receptionRadioMale.setBackground(new java.awt.Color(51, 51, 51));
        receptionGenderButtonGroup.add(receptionRadioMale);
        receptionRadioMale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        receptionRadioMale.setForeground(new java.awt.Color(255, 255, 255));
        receptionRadioMale.setSelected(true);
        receptionRadioMale.setText("Male");
        jPanel8.add(receptionRadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        receptionRadioFemale.setBackground(new java.awt.Color(51, 51, 51));
        receptionGenderButtonGroup.add(receptionRadioFemale);
        receptionRadioFemale.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        receptionRadioFemale.setForeground(new java.awt.Color(255, 255, 255));
        receptionRadioFemale.setText("Female");
        jPanel8.add(receptionRadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel47.setBackground(new java.awt.Color(51, 51, 51));
        jLabel47.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Password");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 90, 30));

        jSeparator40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 190, 10));

        jLabel48.setBackground(new java.awt.Color(51, 51, 51));
        jLabel48.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Re-enter Password");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 140, 30));

        jSeparator41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 190, 10));

        receptionAdminCheck.setBackground(new java.awt.Color(51, 51, 51));
        receptionAdminCheck.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        receptionAdminCheck.setForeground(new java.awt.Color(255, 255, 255));
        receptionAdminCheck.setText("Give administrator privileges");
        receptionAdminCheck.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        receptionAdminCheck.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        receptionAdminCheck.setIconTextGap(6);
        jPanel8.add(receptionAdminCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 330, -1));

        receptionDateOfJob.setBackground(new java.awt.Color(51, 51, 51));
        receptionDateOfJob.setForeground(new java.awt.Color(255, 255, 255));
        receptionDateOfJob.setDateFormatString("yyyy-MM-dd");
        receptionDateOfJob.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        jPanel8.add(receptionDateOfJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 190, -1));

        receptionPassword.setBackground(new java.awt.Color(51, 51, 51));
        receptionPassword.setBorder(null);
        jPanel8.add(receptionPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 190, 30));

        receptionReEnterPassword.setBackground(new java.awt.Color(51, 51, 51));
        receptionReEnterPassword.setBorder(null);
        jPanel8.add(receptionReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 190, 30));

        jTabbedPane1.addTab("Reception", jPanel8);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 480, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doctorConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorConfirmButtonActionPerformed
        //checking for empty required textFields
        if(this.doctorEmployeeId.getText().equals("") || this.doctorName.getText().equals("") || this.doctorAddressLine1.getText().equals("") || this.doctorCity.getText().equals("") ||
                this.doctorContact.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Fill The Empty Fields");
        }else{
            
            //checking for passward compatibility
            if(this.doctorPassword.getText().equals(this.doctorReEnterPassword.getText())){
                
                // assigning input data to variables
                int employee_id = Integer.parseInt(this.doctorEmployeeId.getText());
                String name = this.doctorName.getText();
                String gender = doctorGenderButtonGroup.getElements().nextElement().getText();
                String addressLine1 = this.doctorAddressLine1.getText();
                String addresssLine2 = this.doctorAddressLine2.getText();
                String city = this.doctorCity.getText();
                String specialization = this.doctorSpecialization.getText();
                int contact = Integer.parseInt(this.doctorContact.getText());
                String dateOfJob = ((JTextField)this.doctorDateOfJob.getDateEditor().getUiComponent()).getText();
                String password = this.doctorPassword.getText();
                String adminRight;

                //checking for admin previleges
                if(doctorAdminCheck.isSelected() == true){
                    adminRight = "admin";
                }else{
                    adminRight = "user";
                }

                addEmployeeFinal(employee_id, name, gender, addressLine1, addresssLine2, city, specialization, contact, dateOfJob, "Doctor",password,adminRight);
            }else{
                JOptionPane.showMessageDialog(this,"Passwords Do Not Match");
            }
        }
    }//GEN-LAST:event_doctorConfirmButtonActionPerformed

    private void nurseConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseConfirmButtonActionPerformed
        
        //checking for empty required textFields
        if(this.nurseEmployeeId.getText().equals("") ||this.nurseName.getText().equals("") || this.nurseAddressLine1.getText().equals("") || this.nurseCity.getText().equals("") ||
                this.nurseContact.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Fill The Empty Fields");
        }else{
            
            //checking for passward compatibility
            if(this.nursePassword.getText().equals(this.nurseReEnterPassword.getText())){
                
                // assigning input data to variables
                int employee_id = Integer.parseInt(this.nurseEmployeeId.getText());
                String name = this.nurseName.getText();
                String gender = nurseGenderButtonGroup.getElements().nextElement().getText();
                String addressLine1 = this.nurseAddressLine1.getText();
                String addresssLine2 = this.nurseAddressLine2.getText();
                String city = this.nurseCity.getText();
                int contact = Integer.parseInt(this.nurseContact.getText());
                String dateOfJob = ((JTextField)this.nurseDateOfJob.getDateEditor().getUiComponent()).getText();
                String password = this.nurseReEnterPassword.getText();
                String reEnteredPassword = this.nurseReEnterPassword.getText();
                String adminRight;

                //checking for admin previleges
                if(nurseAdminCheck.isSelected() == true){
                    adminRight = "admin";
                }else{
                    adminRight = "user";
                }

                addEmployeeFinal(employee_id, name, gender, addressLine1, addresssLine2, city, "", contact, dateOfJob, "Nurse",password,adminRight);
            }else{
                JOptionPane.showMessageDialog(this,"Passwords Do Not Match");
            }
        }
    }//GEN-LAST:event_nurseConfirmButtonActionPerformed

    private void maintenanceConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceConfirmButtonActionPerformed
        
        //checking for empty required textFields
        if(this.maintenanceEmployeeId.getText().equals("") ||this.maintenanceName.getText().equals("") || this.maintenanceAddressLine1.getText().equals("") || this.maintenanceCity.getText().equals("") ||
                this.maintenanceContact.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Fill The Empty Fields");
        }else{
            
            //checking for passward compatibility
            if(this.maintenancePassword.getText().equals(this.maintenanceReEnterPassword.getText())){
                
                // assigning input data to variables
                int employee_id = Integer.parseInt(this.maintenanceEmployeeId.getText());
                String name = this.maintenanceName.getText();
                String gender = maintenanceGenderButtonGroup.getElements().nextElement().getText();
                String addressLine1 = this.maintenanceAddressLine1.getText();
                String addresssLine2 = this.maintenanceAddressLine2.getText();
                String city = this.maintenanceCity.getText();
                int contact = Integer.parseInt(this.maintenanceContact.getText());
                String dateOfJob = ((JTextField)this.maintenanceDateOfJob.getDateEditor().getUiComponent()).getText();
                String password = this.maintenancePassword.getText();
                String adminRight;

                //checking for admin previleges
                if(maintenanceAdminCheck.isSelected() == true){
                    adminRight = "admin";
                }else{
                    adminRight = "user";
                }
                addEmployeeFinal(employee_id, name, gender, addressLine1, addresssLine2, city, "", contact, dateOfJob, "Maintenance",password,adminRight);
            }else{
                JOptionPane.showMessageDialog(this,"Passwords Do Not Match");
            }
        }
    }//GEN-LAST:event_maintenanceConfirmButtonActionPerformed

    private void receptionConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionConfirmButtonActionPerformed
        //checking for empty required textFields
        if(this.receptionEmployeeId.getText().equals("") || this.receptionName.getText().equals("") || this.receptionAddressLine1.getText().equals("") || this.receptionCity.getText().equals("") ||
                this.receptionContact.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Fill The Empty Fields");
        }else{
            
             //checking for passward compatibility
            if(this.receptionPassword.getText().equals(this.receptionReEnterPassword.getText())){
                
                // assigning input data to variables
                int employee_id = Integer.parseInt(this.receptionEmployeeId.getText());
                String name = this.receptionName.getText();
                String gender = receptionGenderButtonGroup.getElements().nextElement().getText();
                String addressLine1 = this.receptionAddressLine1.getText();
                String addresssLine2 = this.receptionAddressLine2.getText();
                String city = this.receptionCity.getText();
                int contact = Integer.parseInt(this.receptionContact.getText());
                String dateOfJob = ((JTextField)this.receptionDateOfJob.getDateEditor().getUiComponent()).getText();
                String password = this.receptionPassword.getText();
                String adminRight;
                
                //checking for admin previleges
                if(receptionAdminCheck.isSelected() == true){
                    adminRight = "admin";
                }else{
                    adminRight = "user";
                }

                addEmployeeFinal(employee_id, name, gender, addressLine1, addresssLine2, city, "", contact, dateOfJob, "Reception",password,adminRight);

            }else{
                JOptionPane.showMessageDialog(this,"Passwords Do Not Match");
            }
        }
    }//GEN-LAST:event_receptionConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField doctorAddressLine1;
    private javax.swing.JTextField doctorAddressLine2;
    private javax.swing.JCheckBox doctorAdminCheck;
    private javax.swing.JTextField doctorCity;
    private javax.swing.JButton doctorConfirmButton;
    private javax.swing.JTextField doctorContact;
    private com.toedter.calendar.JDateChooser doctorDateOfJob;
    private javax.swing.JTextField doctorEmployeeId;
    private javax.swing.ButtonGroup doctorGenderButtonGroup;
    private javax.swing.JTextField doctorName;
    private javax.swing.JPasswordField doctorPassword;
    private javax.swing.JRadioButton doctorRadioFemale;
    private javax.swing.JRadioButton doctorRadioMale;
    private javax.swing.JPasswordField doctorReEnterPassword;
    private javax.swing.JTextField doctorSpecialization;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maintenanceAddressLine1;
    private javax.swing.JTextField maintenanceAddressLine2;
    private javax.swing.JCheckBox maintenanceAdminCheck;
    private javax.swing.JTextField maintenanceCity;
    private javax.swing.JButton maintenanceConfirmButton;
    private javax.swing.JTextField maintenanceContact;
    private com.toedter.calendar.JDateChooser maintenanceDateOfJob;
    private javax.swing.JTextField maintenanceEmployeeId;
    private javax.swing.ButtonGroup maintenanceGenderButtonGroup;
    private javax.swing.JTextField maintenanceName;
    private javax.swing.JPasswordField maintenancePassword;
    private javax.swing.JRadioButton maintenanceRadioFemale;
    private javax.swing.JRadioButton maintenanceRadioMale;
    private javax.swing.JPasswordField maintenanceReEnterPassword;
    private javax.swing.JTextField nurseAddressLine1;
    private javax.swing.JTextField nurseAddressLine2;
    private javax.swing.JCheckBox nurseAdminCheck;
    private javax.swing.JTextField nurseCity;
    private javax.swing.JButton nurseConfirmButton;
    private javax.swing.JTextField nurseContact;
    private com.toedter.calendar.JDateChooser nurseDateOfJob;
    private javax.swing.JTextField nurseEmployeeId;
    private javax.swing.ButtonGroup nurseGenderButtonGroup;
    private javax.swing.JTextField nurseName;
    private javax.swing.JPasswordField nursePassword;
    private javax.swing.JRadioButton nurseRadioFemale;
    private javax.swing.JRadioButton nurseRadioMale;
    private javax.swing.JPasswordField nurseReEnterPassword;
    private javax.swing.JTextField receptionAddressLine1;
    private javax.swing.JTextField receptionAddressLine2;
    private javax.swing.JCheckBox receptionAdminCheck;
    private javax.swing.JTextField receptionCity;
    private javax.swing.JButton receptionConfirmButton;
    private javax.swing.JTextField receptionContact;
    private com.toedter.calendar.JDateChooser receptionDateOfJob;
    private javax.swing.JTextField receptionEmployeeId;
    private javax.swing.ButtonGroup receptionGenderButtonGroup;
    private javax.swing.JTextField receptionName;
    private javax.swing.JPasswordField receptionPassword;
    private javax.swing.JRadioButton receptionRadioFemale;
    private javax.swing.JRadioButton receptionRadioMale;
    private javax.swing.JPasswordField receptionReEnterPassword;
    // End of variables declaration//GEN-END:variables
}
