/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import hospital.management.system.connection.AddPatientConnect;
import hospital.management.system.connection.DateTime;
import hospital.management.system.connection.GetDoctorNameList;
import hospital.management.system.connection.GetWardList;
import hospital.management.system.connection.NextPatientId;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hashan
 */
public class AddPatient extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
    public AddPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        patientId = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        recommendation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        addressLine1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        addressLine2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        buttonConfirm = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        contactNumber = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sickness = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        wardCombo = new javax.swing.JComboBox<>();
        confirmationCombo = new javax.swing.JComboBox<>();
        consultantCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 152, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 152, 216));
        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add a Patient");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, 70));

        jLabel7.setBackground(new java.awt.Color(0, 153, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Hospital Management System\\src\\images\\Wheelchair-100.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 120));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 200, 10));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 140, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 670));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Patient ID");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 30));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ward Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 90, 30));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Recommendation");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 30));

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Confirmation");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 90, 30));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Consultant");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 90, 30));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Patient Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 190, 10));

        patientId.setEditable(false);
        patientId.setBackground(new java.awt.Color(51, 51, 51));
        patientId.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        patientId.setForeground(new java.awt.Color(255, 255, 255));
        patientId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        patientId.setBorder(null);
        patientId.setCaretColor(new java.awt.Color(255, 255, 255));
        patientId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        patientId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        patientId.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(patientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 190, 10));

        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        name.setCaretColor(new java.awt.Color(255, 255, 255));
        name.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 190, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 190, 10));

        recommendation.setBackground(new java.awt.Color(51, 51, 51));
        recommendation.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        recommendation.setForeground(new java.awt.Color(255, 255, 255));
        recommendation.setBorder(null);
        recommendation.setCaretColor(new java.awt.Color(255, 255, 255));
        recommendation.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(recommendation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 190, 30));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Patient Name");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 30));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 30));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address Line 1");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 90, 30));

        addressLine1.setBackground(new java.awt.Color(51, 51, 51));
        addressLine1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        addressLine1.setForeground(new java.awt.Color(255, 255, 255));
        addressLine1.setBorder(null);
        addressLine1.setCaretColor(new java.awt.Color(255, 255, 255));
        addressLine1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(addressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 190, 30));

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 10));

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address Line 2");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 30));

        addressLine2.setBackground(new java.awt.Color(51, 51, 51));
        addressLine2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        addressLine2.setForeground(new java.awt.Color(255, 255, 255));
        addressLine2.setBorder(null);
        addressLine2.setCaretColor(new java.awt.Color(255, 255, 255));
        addressLine2.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(addressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 190, 30));

        jSeparator13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 10));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("City");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, 30));

        city.setBackground(new java.awt.Color(51, 51, 51));
        city.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setBorder(null);
        city.setCaretColor(new java.awt.Color(255, 255, 255));
        city.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 190, 30));

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 190, 10));

        buttonConfirm.setBackground(new java.awt.Color(0, 152, 216));
        buttonConfirm.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        buttonConfirm.setForeground(new java.awt.Color(255, 255, 255));
        buttonConfirm.setText("Confirm");
        buttonConfirm.setBorder(null);
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });
        jPanel2.add(buttonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 110, 40));

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("NIC");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 30));

        nic.setBackground(new java.awt.Color(51, 51, 51));
        nic.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        nic.setForeground(new java.awt.Color(255, 255, 255));
        nic.setBorder(null);
        nic.setCaretColor(new java.awt.Color(255, 255, 255));
        nic.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 190, 30));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 10));

        contactNumber.setBackground(new java.awt.Color(51, 51, 51));
        contactNumber.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        contactNumber.setForeground(new java.awt.Color(255, 255, 255));
        contactNumber.setBorder(null);
        contactNumber.setCaretColor(new java.awt.Color(255, 255, 255));
        contactNumber.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(contactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 190, 30));

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 190, 10));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Contact Number");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 30));

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Sickness");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 100, 30));

        sickness.setBackground(new java.awt.Color(51, 51, 51));
        sickness.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        sickness.setForeground(new java.awt.Color(255, 255, 255));
        sickness.setBorder(null);
        sickness.setCaretColor(new java.awt.Color(255, 255, 255));
        sickness.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(sickness, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 190, 30));

        jSeparator16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 190, 10));

        radioMale.setBackground(new java.awt.Color(51, 51, 51));
        genderButtonGroup.add(radioMale);
        radioMale.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        radioMale.setForeground(new java.awt.Color(255, 255, 255));
        radioMale.setSelected(true);
        radioMale.setText("Male");
        jPanel2.add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        radioFemale.setBackground(new java.awt.Color(51, 51, 51));
        genderButtonGroup.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        radioFemale.setForeground(new java.awt.Color(255, 255, 255));
        radioFemale.setText("Female");
        jPanel2.add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jPanel2.add(wardCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 70, 30));

        confirmationCombo.setBackground(new java.awt.Color(51, 51, 51));
        confirmationCombo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        confirmationCombo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(confirmationCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 487, 190, 40));

        consultantCombo.setBackground(new java.awt.Color(51, 51, 51));
        consultantCombo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        consultantCombo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(consultantCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 537, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 480, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // returns the ID of the next patient,ward list and doctor name list
    public void getIndex() {

        //get the next patient id from the patient list
        NextPatientId nextPatient = new NextPatientId();
        int count = nextPatient.getNextId();
        patientId.setText(String.valueOf(count));

        //add the ward list to the combo box
        GetWardList wardList = new GetWardList();
        ArrayList<Integer> wards = wardList.getWardList();
        for (int item : wards) {
            wardCombo.addItem(String.valueOf(item));
        }

        //add the doctor name list to the two combo boxes
        GetDoctorNameList doctorList = new GetDoctorNameList();
        ArrayList<String> doctors = doctorList.getDoctorList();
        for (String item : doctors) {
            consultantCombo.addItem(item);
            confirmationCombo.addItem(item);
        }
    }
    
    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed
        //checks for the required empty text fields
        if(this.name.getText().equals("") || this.nic.getText().equals("") || this.addressLine1.getText().equals("") || 
                this.city.getText().equals("") || this.contactNumber.getText().equals("") || this.recommendation.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Fill The Empty Fields");
        }else{
            // get the user inputs
            int patientId = Integer.parseInt(this.patientId.getText());
            String name = this.name.getText();
            int nic = Integer.parseInt(this.nic.getText());
            String gender = genderButtonGroup.getElements().nextElement().getText();
            String admitDate = new DateTime().getDate().toString();
            String admitTime = new DateTime().getTime().toString();
            String addressLine1 = this.addressLine1.getText();
            String addresssLine2 = this.addressLine2.getText();
            String city = this.city.getText();
            int contactNumber = Integer.parseInt(this.contactNumber.getText());
            String sickness = this.sickness.getText();
            int ward = Integer.parseInt((String) this.wardCombo.getSelectedItem());
            String recommendation = this.recommendation.getText();
            String confirmation = String.valueOf(this.confirmationCombo.getSelectedItem());
            String consultant = String.valueOf(this.consultantCombo.getSelectedItem());

            //adding to the database
            AddPatientConnect addConnect = new AddPatientConnect();
            int result = addConnect.updateData(patientId, name, nic, gender, admitDate, admitTime, addressLine1,
                    addresssLine2, city, contactNumber, sickness,
                    ward, recommendation, confirmation, consultant);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Successfull");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed");
            }
        }
    }//GEN-LAST:event_buttonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressLine1;
    private javax.swing.JTextField addressLine2;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> confirmationCombo;
    private javax.swing.JComboBox<String> consultantCombo;
    private javax.swing.JTextField contactNumber;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField patientId;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField recommendation;
    private javax.swing.JTextField sickness;
    private javax.swing.JComboBox<String> wardCombo;
    // End of variables declaration//GEN-END:variables
}
