/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import hospital.management.system.connection.DBConnect;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hashan
 */
public class AddWeight extends javax.swing.JFrame {

    /**
     * Creates new form Weight
     */
    
    //initializing global variables
    private int patientNic;
    private Connection con;

    public AddWeight() {
        initComponents();
    }

    //overiding contructor
    public AddWeight(int patientNic) {
        initComponents();
        this.patientNic = patientNic;
    }

    //creating the database connection
    public void createConnectoin() {
        DBConnect db = new DBConnect();
        this.con = db.createConnection();
    }

    public void updateData() {
        
        // checks for the empty field
        if(weight.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Weight Cannot Be Empty");
        }else{
            //updating the database
            try {
                int patientWeight = Integer.parseInt(weight.getText());
                PreparedStatement ps = con.prepareStatement("update patient set weight=? where nic=?");
                ps.setInt(1, patientWeight);
                ps.setInt(2, patientNic);

                int result = ps.executeUpdate();

                if (result == 1) {

                    JOptionPane.showMessageDialog(this, "Weight Updated");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Update Failed");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Only Enter Numbers");
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultantName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        weight = new javax.swing.JTextField();
        unit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultantName.setBackground(new java.awt.Color(51, 51, 51));
        consultantName.setFont(new java.awt.Font("Quicksand", 0, 36)); // NOI18N
        consultantName.setForeground(new java.awt.Color(217, 222, 225));
        consultantName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultantName.setText("Add Weight");
        jPanel1.add(consultantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 240, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 90));

        jPanel2.setBackground(new java.awt.Color(67, 101, 112));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        weight.setBackground(new java.awt.Color(67, 101, 112));
        weight.setFont(new java.awt.Font("Quicksand", 0, 36)); // NOI18N
        weight.setForeground(new java.awt.Color(217, 222, 225));
        weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        weight.setBorder(null);
        weight.setCaretColor(new java.awt.Color(255, 255, 255));
        weight.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                weightKeyPressed(evt);
            }
        });
        jPanel2.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 60));

        unit.setBackground(new java.awt.Color(67, 101, 112));
        unit.setFont(new java.awt.Font("Quicksand", 0, 36)); // NOI18N
        unit.setForeground(new java.awt.Color(217, 222, 225));
        unit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unit.setText("Kg");
        jPanel2.add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 70, 50));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void weightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightKeyPressed
        //checks for the enter key press
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            updateData();
        }

        //checks for the escape key press
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_weightKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWeight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultantName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel unit;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
