/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import hospital.management.system.connection.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hashan
 */
public class EnterResults extends javax.swing.JFrame {

    /**
     * Creates new form EnterResults
     */
    
    // global variables
    private int patientId;
    private String testName;
    private int testNumber;
    private int nurseId;
    private Connection con;
    
    public EnterResults() {
        initComponents();
    }
    
    // override the constructor and inialize the variable
    public EnterResults(int patientId, String testName,int testNumber, int nurseId) {
        initComponents();
        this.patientId = patientId;
        this.testName = testName;
        this.nurseId = nurseId;
        this.testNumber = testNumber;
    }
    
    //create database connection
    public void createConnection(){
         DBConnect db = new DBConnect();
         this.con = db.createConnection();
    }
    
    //set the labels
    public void setValues(){
        this.patientIdLabel.setText(String.valueOf(patientId));
        this.testNameLabel.setText(testName);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultantName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        testNameLabel = new javax.swing.JLabel();
        patientIdLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultText = new javax.swing.JTextField();
        buttonCancel = new javax.swing.JButton();
        buttonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultantName.setBackground(new java.awt.Color(51, 51, 51));
        consultantName.setFont(new java.awt.Font("Quicksand", 0, 36)); // NOI18N
        consultantName.setForeground(new java.awt.Color(217, 222, 225));
        consultantName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultantName.setText("Add Result");
        jPanel1.add(consultantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 110));

        jPanel2.setBackground(new java.awt.Color(67, 101, 112));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 410, 10));

        testNameLabel.setBackground(new java.awt.Color(67, 101, 112));
        testNameLabel.setFont(new java.awt.Font("Quicksand", 0, 24)); // NOI18N
        testNameLabel.setForeground(new java.awt.Color(217, 222, 225));
        testNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        testNameLabel.setText("Test Name");
        jPanel2.add(testNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 160, 60));

        patientIdLabel.setBackground(new java.awt.Color(67, 101, 112));
        patientIdLabel.setFont(new java.awt.Font("Quicksand", 0, 24)); // NOI18N
        patientIdLabel.setForeground(new java.awt.Color(217, 222, 225));
        patientIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientIdLabel.setText("Patient ID");
        jPanel2.add(patientIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 60));

        jLabel6.setBackground(new java.awt.Color(67, 101, 112));
        jLabel6.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TEST NAME");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 120, 30));

        jLabel7.setBackground(new java.awt.Color(67, 101, 112));
        jLabel7.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PATIENT ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, 30));

        resultText.setBackground(new java.awt.Color(67, 101, 112));
        resultText.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        resultText.setForeground(new java.awt.Color(255, 255, 255));
        resultText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultText.setBorder(null);
        resultText.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(resultText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 410, 60));

        buttonCancel.setBackground(new java.awt.Color(51, 51, 51));
        buttonCancel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancel.setText("CANCEL");
        buttonCancel.setBorder(null);
        buttonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, 30));

        buttonOk.setBackground(new java.awt.Color(51, 51, 51));
        buttonOk.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttonOk.setForeground(new java.awt.Color(255, 255, 255));
        buttonOk.setText("OK");
        buttonOk.setBorder(null);
        buttonOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        jPanel2.add(buttonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 90, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 570, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        
        //updating the database patient_test table by taking the user input
        String result = resultText.getText();
        try{
            PreparedStatement ps = con.prepareStatement("update patient_test set result = ?,updatedBy = ? where test_number = ?");
            ps.setString(1, result);
            ps.setInt(2, nurseId);
            ps.setInt(3, testNumber);

            int updateResult = ps.executeUpdate();
            if(updateResult == 1){
                JOptionPane.showMessageDialog(this, "Update Successful");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_buttonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel consultantName;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JTextField resultText;
    private javax.swing.JLabel testNameLabel;
    // End of variables declaration//GEN-END:variables
}
