/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import hospital.management.system.connection.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hashan
 */
public class PatientHistory extends javax.swing.JFrame {

    /**
     * Creates new form PatientHistory
     */
    
    //global variables
    private int patientNic;
    private Connection con;
    
    public PatientHistory() {
        initComponents();
    }
    
    // constructor overloading
    public PatientHistory(int patientNic) {
        initComponents();
        this.patientNic = patientNic;
    }
    
    //create the database connection
    public void createConnectoin() {
        DBConnect db = new DBConnect();
        this.con = db.createConnection();
    }
    
    // display the patient's early records
    public void setDisplay(){
        
        try {
            PreparedStatement ps = con.prepareStatement("select * from patient where nic = ? and discharge_date is not null");
            ps.setInt(1, patientNic);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String patientName = rs.getString("name");
                String admitDate = rs.getString("admit_date");
                String sickness = rs.getString("sickness");
                int consultant = rs.getInt("consultant");
                String dischargeDate = rs.getString("discharge_date");
                
                patientNameLabel.setText(patientName);
                patientNicLabel.setText(String.valueOf(patientNic));
                
                // get the name from the employee id
                PreparedStatement pst = con.prepareStatement("select name from employee where employee_id = ?");
                pst.setInt(1, consultant);
                ResultSet rst = pst.executeQuery();
                
                while(rst.next()){
                    String name = rst.getString("name");
                    
                    DefaultTableModel tableModel = (DefaultTableModel) historyTable.getModel();
                    tableModel.addRow(new Object[] {admitDate,sickness,name,dischargeDate});
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PatientHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        patientNameLabel = new javax.swing.JLabel();
        patientNicLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(67, 101, 112));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User-100.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        patientNameLabel.setBackground(new java.awt.Color(0, 152, 216));
        patientNameLabel.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        patientNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientNameLabel.setText("Patient Name");
        jPanel1.add(patientNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 290, 40));

        patientNicLabel.setBackground(new java.awt.Color(0, 152, 216));
        patientNicLabel.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        patientNicLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientNicLabel.setText("NIC");
        jPanel1.add(patientNicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 100));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        historyTable.setBackground(new java.awt.Color(51, 51, 51));
        historyTable.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        historyTable.setForeground(new java.awt.Color(255, 255, 255));
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admit Date", "Sickness", "Consultant", "Discharge Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historyTable.setGridColor(new java.awt.Color(51, 51, 51));
        historyTable.setRowHeight(50);
        historyTable.setShowHorizontalLines(false);
        historyTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(historyTable);
        if (historyTable.getColumnModel().getColumnCount() > 0) {
            historyTable.getColumnModel().getColumn(0).setResizable(false);
            historyTable.getColumnModel().getColumn(1).setResizable(false);
            historyTable.getColumnModel().getColumn(2).setResizable(false);
            historyTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 710, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel patientNicLabel;
    // End of variables declaration//GEN-END:variables
}
