/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import hospital.management.system.connection.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hashan
 */
public class TestResults extends javax.swing.JFrame{

    /**
     * Creates new form TestResults
     */
    
    //global valriables
    private Connection con;
    
    public TestResults() {
        initComponents();
    }
    
    
    public TestResults(int patientNic, String patientName) {
        initComponents();
    }
    
    //create the database connection
    public void createConnectoin() {
        DBConnect db = new DBConnect();
        this.con = db.createConnection();
    }
    
    // fill the table with test results of given patient
    public void fillTable(int patientNic, String patientName){
        
        patientNameLabel.setText(patientName);
        patientNicLabel.setText(String.valueOf(patientNic));
        
        try {
            PreparedStatement ps = con.prepareStatement("select * from patient_test where nic = ? and result is NULL");
            ps.setInt(1, patientNic);

            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                int testId = rs.getInt("test_id");
                int recommendation = rs.getInt("recommendation");
                String date = rs.getString("date");
                String time = rs.getString("time");
                String result = rs.getString("result");
                String recommendedNBy = "";
                String testName = "";   

                PreparedStatement pst = con.prepareStatement("select name from employee where employee_id = ?");
                pst.setInt(1, recommendation);
                ResultSet rst = pst.executeQuery();
                
                while(rst.next()){
                    recommendedNBy = rst.getString("name");
                    
                    PreparedStatement pss = con.prepareStatement("select * from test where test_id = ?");
                    pss.setInt(1, testId);
                    ResultSet rss = pss.executeQuery();
                    
                    while(rss.next()){
                        testName = rss.getString("test_name");
                        
                        DefaultTableModel tableModel = (DefaultTableModel) testResultTable.getModel();
                        tableModel.addRow(new Object[] {testName,recommendedNBy,date,time,result});
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Results Fetching Failed");
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        patientNicLabel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        patientNameLabel = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        testResultTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 152, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 152, 216));
        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Test Results");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, 70));

        jLabel7.setBackground(new java.awt.Color(0, 153, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Hospital Management System\\src\\images\\Test Passed-100.png")); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 100, 130));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, 10));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 140, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 540));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Patient NIC");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 30));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Patient Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 30));

        patientNicLabel.setEditable(false);
        patientNicLabel.setBackground(new java.awt.Color(51, 51, 51));
        patientNicLabel.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        patientNicLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientNicLabel.setBorder(null);
        patientNicLabel.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(patientNicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, 10));

        patientNameLabel.setEditable(false);
        patientNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        patientNameLabel.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        patientNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientNameLabel.setBorder(null);
        patientNameLabel.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(patientNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, 10));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        testResultTable.setBackground(new java.awt.Color(51, 51, 51));
        testResultTable.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        testResultTable.setForeground(new java.awt.Color(255, 255, 255));
        testResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Name", "Remmended By", "Date", "Time", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testResultTable.setGridColor(new java.awt.Color(0, 152, 216));
        testResultTable.setRowHeight(50);
        testResultTable.setSelectionBackground(new java.awt.Color(0, 152, 216));
        testResultTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(testResultTable);
        if (testResultTable.getColumnModel().getColumnCount() > 0) {
            testResultTable.getColumnModel().getColumn(0).setResizable(false);
            testResultTable.getColumnModel().getColumn(1).setResizable(false);
            testResultTable.getColumnModel().getColumn(2).setResizable(false);
            testResultTable.getColumnModel().getColumn(3).setResizable(false);
            testResultTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 750, 350));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 770, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField patientNameLabel;
    private javax.swing.JTextField patientNicLabel;
    private javax.swing.JTable testResultTable;
    // End of variables declaration//GEN-END:variables
}
